# Generated by Django 3.1.7 on 2021-02-20 14:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('UB', 'Unblocked/Free'), ('BL', 'Blocked/Unavailable')], default='UB', max_length=2)),
            ],
        ),
    ]
