# Generated by Django 3.1.7 on 2021-02-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_token_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='allocated_till',
            field=models.DateField(default=None, null=True),
        ),
    ]
