# Generated by Django 3.1.7 on 2021-02-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0005_auto_20210220_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='token',
            name='updated_on',
        ),
    ]
