# Generated by Django 3.1.7 on 2021-02-20 16:27

from django.db import migrations, models
import pool.models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0002_auto_20210220_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='expiry',
            field=models.DateTimeField(default=pool.models.get_expiry),
        ),
    ]
