# Generated by Django 3.1.7 on 2021-02-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0004_token_allocated_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='allocated_till',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
